[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all redirect (MUST be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
