[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Static files first (prevent catch-all from intercepting)
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = false

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all redirect (MUST be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200